In [ ]:
import polars as pl
import os
from dotenv import load_dotenv
load_dotenv()

In [ ]:
BASE_PATH = os.environ.get("BASE_PATH")
df = pl.read_parquet(
        f"{BASE_PATH}/data/processed/df_merged.parquet",
        columns=["item_store_id", "day_number", "sales"]
    )

In [21]:
df = df.sort(["item_store_id", "day_number"])

In [22]:
df = df.with_columns([
    pl.col("sales").shift(1).rolling_mean(7).over("item_store_id").alias("rolling_mean_7"),
])

In [23]:
df.head(20)

shape: (20, 4)
┌─────────────────────────────┬────────────┬───────┬────────────────┐
│ item_store_id               ┆ day_number ┆ sales ┆ rolling_mean_7 │
│ ---                         ┆ ---        ┆ ---   ┆ ---            │
│ str                         ┆ i16        ┆ i16   ┆ f64            │
╞═════════════════════════════╪════════════╪═══════╪════════════════╡
│ FOODS_1_001_CA_1_evaluation ┆ 1          ┆ 3     ┆ null           │
│ FOODS_1_001_CA_1_evaluation ┆ 2          ┆ 0     ┆ null           │
│ FOODS_1_001_CA_1_evaluation ┆ 3          ┆ 0     ┆ null           │
│ FOODS_1_001_CA_1_evaluation ┆ 4          ┆ 1     ┆ null           │
│ FOODS_1_001_CA_1_evaluation ┆ 5          ┆ 4     ┆ null           │
│ …                           ┆ …          ┆ …     ┆ …              │
│ FOODS_1_001_CA_1_evaluation ┆ 16         ┆ 0     ┆ 1.0            │
│ FOODS_1_001_CA_1_evaluation ┆ 17         ┆ 2     ┆ 1.0            │
│ FOODS_1_001_CA_1_evaluation ┆ 18         ┆ 1     ┆ 1.285714       │
│ FOODS_1_001_CA_1_evaluation ┆ 19         ┆ 2     ┆ 1.428571       │
│ FOODS_1_001_CA_1_evaluation ┆ 20         ┆ 0     ┆ 1.714286       │
└─────────────────────────────┴────────────┴───────┴────────────────┘

In [24]:
# Monthly trends
df = df.with_columns(
    pl.col("sales").shift(1).rolling_mean(28).over('item_store_id').alias('rolling_mean_28')
)

In [25]:
df = df.with_columns(
    pl.col('sales').shift(1).rolling_std(7).over('item_store_id').alias('rolling_std_7')
)

In [26]:
df.head(10)

shape: (10, 6)
┌──────────────────────────┬────────────┬───────┬────────────────┬─────────────────┬───────────────┐
│ item_store_id            ┆ day_number ┆ sales ┆ rolling_mean_7 ┆ rolling_mean_28 ┆ rolling_std_7 │
│ ---                      ┆ ---        ┆ ---   ┆ ---            ┆ ---             ┆ ---           │
│ str                      ┆ i16        ┆ i16   ┆ f64            ┆ f64             ┆ f64           │
╞══════════════════════════╪════════════╪═══════╪════════════════╪═════════════════╪═══════════════╡
│ FOODS_1_001_CA_1_evaluat ┆ 1          ┆ 3     ┆ null           ┆ null            ┆ null          │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 2          ┆ 0     ┆ null           ┆ null            ┆ null          │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 3          ┆ 0     ┆ null           ┆ null            ┆ null          │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 4          ┆ 1     ┆ null           ┆ null            ┆ null          │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 5          ┆ 4     ┆ null           ┆ null            ┆ null          │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 6          ┆ 2     ┆ null           ┆ null            ┆ null          │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 7          ┆ 0     ┆ null           ┆ null            ┆ null          │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 8          ┆ 2     ┆ 1.428571       ┆ null            ┆ 1.618347      │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 9          ┆ 0     ┆ 1.285714       ┆ null            ┆ 1.496026      │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
│ FOODS_1_001_CA_1_evaluat ┆ 10         ┆ 0     ┆ 1.285714       ┆ null            ┆ 1.496026      │
│ ion                      ┆            ┆       ┆                ┆                 ┆               │
└──────────────────────────┴────────────┴───────┴────────────────┴─────────────────┴───────────────┘