In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
load_dotenv()

In [ ]:
BASE_PATH = os.environ.get("BASE_PATH")
sales = pd.read_csv(f'{BASE_PATH}/data/raw/sales_train_evaluation.csv')
pd.set_option('display.max_columns', None)
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,d_26,d_27,d_28,d_29,d_30,d_31,d_32,d_33,d_34,d_35,d_36,d_37,d_38,d_39,d_40,d_41,d_42,d_43,d_44,d_45,d_46,d_47,d_48,d_49,d_50,d_51,d_52,d_53,d_54,d_55,d_56,d_57,d_58,d_59,d_60,d_61,d_62,d_63,d_64,d_65,d_66,d_67,d_68,d_69,d_70,d_71,d_72,d_73,d_74,d_75,d_76,d_77,d_78,d_79,d_80,d_81,d_82,d_83,d_84,d_85,d_86,d_87,d_88,d_89,d_90,d_91,d_92,d_93,d_94,d_95,d_96,d_97,d_98,d_99,d_100,d_101,d_102,d_103,d_104,d_105,d_106,d_107,d_108,d_109,d_110,d_111,d_112,d_113,d_114,d_115,d_116,d_117,d_118,d_119,d_120,d_121,d_122,d_123,d_124,d_125,d_126,d_127,d_128,d_129,d_130,d_131,d_132,d_133,d_134,d_135,d_136,d_137,d_138,d_139,d_140,d_141,d_142,d_143,d_144,d_145,d_146,d_147,d_148,d_149,d_150,d_151,d_152,d_153,d_154,d_155,d_156,d_157,d_158,d_159,d_160,d_161,d_162,d_163,d_164,d_165,d_166,d_167,d_168,d_169,d_170,d_171,d_172,d_173,d_174,d_175,d_176,d_177,d_178,d_179,d_180,d_181,d_182,d_183,d_184,d_185,d_186,d_187,d_188,d_189,d_190,d_191,d_192,d_193,d_194,d_195,d_196,d_197,d_198,d_199,d_200,d_201,d_202,d_203,d_204,d_205,d_206,d_207,d_208,d_209,d_210,d_211,d_212,d_213,d_214,d_215,d_216,d_217,d_218,d_219,d_220,d_221,d_222,d_223,d_224,d_225,d_226,d_227,d_228,d_229,d_230,d_231,d_232,d_233,d_234,d_235,d_236,d_237,d_238,d_239,d_240,d_241,d_242,d_243,d_244,d_245,d_246,d_247,d_248,d_249,d_250,d_251,d_252,d_253,d_254,d_255,d_256,d_257,d_258,d_259,d_260,d_261,d_262,d_263,d_264,d_265,d_266,d_267,d_268,d_269,d_270,d_271,d_272,d_273,d_274,d_275,d_276,d_277,d_278,d_279,d_280,d_281,d_282,d_283,d_284,d_285,d_286,d_287,d_288,d_289,d_290,d_291,d_292,d_293,d_294,d_295,d_296,d_297,d_298,d_299,d_300,d_301,d_302,d_303,d_304,d_305,d_306,d_307,d_308,d_309,d_310,d_311,d_312,d_313,d_314,d_315,d_316,d_317,d_318,d_319,d_320,d_321,d_322,d_323,d_324,d_325,d_326,d_327,d_328,d_329,d_330,d_331,d_332,d_333,d_334,d_335,d_336,d_337,d_338,d_339,d_340,d_341,d_342,d_343,d_344,d_345,d_346,d_347,d_348,d_349,d_350,d_351,d_352,d_353,d_354,d_355,d_356,d_357,d_358,d_359,d_360,d_361,d_362,d_363,d_364,d_365,d_366,d_367,d_368,d_369,d_370,d_371,d_372,d_373,d_374,d_375,d_376,d_377,d_378,d_379,d_380,d_381,d_382,d_383,d_384,d_385,d_386,d_387,d_388,d_389,d_390,d_391,d_392,d_393,d_394,d_395,d_396,d_397,d_398,d_399,d_400,d_401,d_402,d_403,d_404,d_405,d_406,d_407,d_408,d_409,d_410,d_411,d_412,d_413,d_414,d_415,d_416,d_417,d_418,d_419,d_420,d_421,d_422,d_423,d_424,d_425,d_426,d_427,d_428,d_429,d_430,d_431,d_432,d_433,d_434,d_435,d_436,d_437,d_438,d_439,d_440,d_441,d_442,d_443,d_444,d_445,d_446,d_447,d_448,d_449,d_450,d_451,d_452,d_453,d_454,d_455,d_456,d_457,d_458,d_459,d_460,d_461,d_462,d_463,d_464,d_465,d_466,d_467,d_468,d_469,d_470,d_471,d_472,d_473,d_474,d_475,d_476,d_477,d_478,d_479,d_480,d_481,d_482,d_483,d_484,d_485,d_486,d_487,d_488,d_489,d_490,d_491,d_492,d_493,d_494,d_495,d_496,d_497,d_498,d_499,d_500,d_501,d_502,d_503,d_504,d_505,d_506,d_507,d_508,d_509,d_510,d_511,d_512,d_513,d_514,d_515,d_516,d_517,d_518,d_519,d_520,d_521,d_522,d_523,d_524,d_525,d_526,d_527,d_528,d_529,d_530,d_531,d_532,d_533,d_534,d_535,d_536,d_537,d_538,d_539,d_540,d_541,d_542,d_543,d_544,d_545,d_546,d_547,d_548,d_549,d_550,d_551,d_552,d_553,d_554,d_555,d_556,d_557,d_558,d_559,d_560,d_561,d_562,d_563,d_564,d_565,d_566,d_567,d_568,d_569,d_570,d_571,d_572,d_573,d_574,d_575,d_576,d_577,d_578,d_579,d_580,d_581,d_582,d_583,d_584,d_585,d_586,d_587,d_588,d_589,d_590,d_591,d_592,d_593,d_594,d_595,d_596,d_597,d_598,d_599,d_600,d_601,d_602,d_603,d_604,d_605,d_606,d_607,d_608,d_609,d_610,d_611,d_612,d_613,d_614,d_615,d_616,d_617,d_618,d_619,d_620,d_621,d_622,d_623,d_624,d_625,d_626,d_627,d_628,d_629,d_630,d_631,d_632,d_633,d_634,d_635,d_636,d_637,d_638,d_639,d_640,d_641,d_642,d_643,d_644,d_645,d_646,d_647,d_648,d_649,d_650,d_651,d_652,d_653,d_654,d_655,d_656,d_657,d_658,d_659,d_660,d_661,d_662,d_663,d_664,d_665,d_666,d_667,d_668,d_669,d_670,d_671,d_672,d_673,d_674,d_675,d_676,d_677,d_678,d_679,d_680,d_681,d_682,d_683,d_684,d_685,d_686,d_687,d_688,d_689,d_690,d_691,d_692,d_693,d_694,d_695,d_696,d_697,d_698,d_699,d_700,d_701,d_702,d_703,d_704,d_705,d_706,d_707,d_708,d_709,d_710,d_711,d_712,d_713,d_714,d_715,d_716,d_717,d_718,d_719,d_720,d_721,d_722,d_723,d_724,d_725,d_726,d_727,d_728,d_729,d_730,d_731,d_732,d_733,d_734,d_735,d_736,d_737,d_738,d_739,d_740,d_741,d_742,d_743,d_744,d_745,d_746,d_747,d_748,d_749,d_750,d_751,d_752,d_753,d_754,d_755,d_756,d_757,d_758,d_759,d_760,d_761,d_762,d_763,d_764,d_765,d_766,d_767,d_768,d_769,d_770,d_771,d_772,d_773,d_774,d_775,d_776,d_777,d_778,d_779,d_780,d_781,d_782,d_783,d_784,d_785,d_786,d_787,d_788,d_789,d_790,d_791,d_792,d_793,d_794,d_795,d_796,d_797,d_798,d_799,d_800,d_801,d_802,d_803,d_804,d_805,d_806,d_807,d_808,d_809,d_810,d_811,d_812,d_813,d_814,d_815,d_816,d_817,d_818,d_819,d_820,d_821,d_822,d_823,d_824,d_825,d_826,d_827,d_828,d_829,d_830,d_831,d_832,d_833,d_834,d_835,d_836,d_837,d_838,d_839,d_840,d_841,d_842,d_843,d_844,d_845,d_846,d_847,d_848,d_849,d_850,d_851,d_852,d_853,d_854,d_855,d_856,d_857,d_858,d_859,d_860,d_861,d_862,d_863,d_864,d_865,d_866,d_867,d_868,d_869,d_870,d_871,d_872,d_873,d_874,d_875,d_876,d_877,d_878,d_879,d_880,d_881,d_882,d_883,d_884,d_885,d_886,d_887,d_888,d_889,d_890,d_891,d_892,d_893,d_894,d_895,d_896,d_897,d_898,d_899,d_900,d_901,d_902,d_903,d_904,d_905,d_906,d_907,d_908,d_909,d_910,d_911,d_912,d_913,d_914,d_915,d_916,d_917,d_918,d_919,d_920,d_921,d_922,d_923,d_924,d_925,d_926,d_927,d_928,d_929,d_930,d_931,d_932,d_933,d_934,d_935,d_936,d_937,d_938,d_939,d_940,d_941,d_942,d_943,d_944,d_945,d_946,d_947,d_948,d_949,d_950,d_951,d_952,d_953,d_954,d_955,d_956,d_957,d_958,d_959,d_960,d_961,d_962,d_963,d_964,d_965,d_966,d_967,d_968,d_969,d_970,d_971,d_972,d_973,d_974,d_975,d_976,d_977,d_978,d_979,d_980,d_981,d_982,d_983,d_984,d_985,d_986,d_987,d_988,d_989,d_990,d_991,d_992,d_993,d_994,d_995,d_996,d_997,d_998,d_999,d_1000,d_1001,d_1002,d_1003,d_1004,d_1005,d_1006,d_1007,d_1008,d_1009,d_1010,d_1011,d_1012,d_1013,d_1014,d_1015,d_1016,d_1017,d_1018,d_1019,d_1020,d_1021,d_1022,d_1023,d_1024,d_1025,d_1026,d_1027,d_1028,d_1029,d_1030,d_1031,d_1032,d_1033,d_1034,d_1035,d_1036,d_1037,d_1038,d_1039,d_1040,d_1041,d_1042,d_1043,d_1044,d_1045,d_1046,d_1047,d_1048,d_1049,d_1050,d_1051,d_1052,d_1053,d_1054,d_1055,d_1056,d_1057,d_1058,d_1059,d_1060,d_1061,d_1062,d_1063,d_1064,d_1065,d_1066,d_1067,d_1068,d_1069,d_1070,d_1071,d_1072,d_1073,d_1074,d_1075,d_1076,d_1077,d_1078,d_1079,d_1080,d_1081,d_1082,d_1083,d_1084,d_1085,d_1086,d_1087,d_1088,d_1089,d_1090,d_1091,d_1092,d_1093,d_1094,d_1095,d_1096,d_1097,d_1098,d_1099,d_1100,d_1101,d_1102,d_1103,d_1104,d_1105,d_1106,d_1107,d_1108,d_1109,d_1110,d_1111,d_1112,d_1113,d_1114,d_1115,d_1116,d_1117,d_1118,d_1119,d_1120,d_1121,d_1122,d_1123,d_1124,d_1125,d_1126,d_1127,d_1128,d_1129,d_1130,d_1131,d_1132,d_1133,d_1134,d_1135,d_1136,d_1137,d_1138,d_1139,d_1140,d_1141,d_1142,d_1143,d_1144,d_1145,d_1146,d_1147,d_1148,d_1149,d_1150,d_1151,d_1152,d_1153,d_1154,d_1155,d_1156,d_1157,d_1158,d_1159,d_1160,d_1161,d_1162,d_1163,d_1164,d_1165,d_1166,d_1167,d_1168,d_1169,d_1170,d_1171,d_1172,d_1173,d_1174,d_1175,d_1176,d_1177,d_1178,d_1179,d_1180,d_1181,d_1182,d_1183,d_1184,d_1185,d_1186,d_1187,d_1188,d_1189,d_1190,d_1191,d_1192,d_1193,d_1194,d_1195,d_1196,d_1197,d_1198,d_1199,d_1200,d_1201,d_1202,d_1203,d_1204,d_1205,d_1206,d_1207,d_1208,d_1209,d_1210,d_1211,d_1212,d_1213,d_1214,d_1215,d_1216,d_1217,d_1218,d_1219,d_1220,d_1221,d_1222,d_1223,d_1224,d_1225,d_1226,d_1227,d_1228,d_1229,d_1230,d_1231,d_1232,d_1233,d_1234,d_1235,d_1236,d_1237,d_1238,d_1239,d_1240,d_1241,d_1242,d_1243,d_1244,d_1245,d_1246,d_1247,d_1248,d_1249,d_1250,d_1251,d_1252,d_1253,d_1254,d_1255,d_1256,d_1257,d_1258,d_1259,d_1260,d_1261,d_1262,d_1263,d_1264,d_1265,d_1266,d_1267,d_1268,d_1269,d_1270,d_1271,d_1272,d_1273,d_1274,d_1275,d_1276,d_1277,d_1278,d_1279,d_1280,d_1281,d_1282,d_1283,d_1284,d_1285,d_1286,d_1287,d_1288,d_1289,d_1290,d_1291,d_1292,d_1293,d_1294,d_1295,d_1296,d_1297,d_1298,d_1299,d_1300,d_1301,d_1302,d_1303,d_1304,d_1305,d_1306,d_1307,d_1308,d_1309,d_1310,d_1311,d_1312,d_1313,d_1314,d_1315,d_1316,d_1317,d_1318,d_1319,d_1320,d_1321,d_1322,d_1323,d_1324,d_1325,d_1326,d_1327,d_1328,d_1329,d_1330,d_1331,d_1332,d_1333,d_1334,d_1335,d_1336,d_1337,d_1338,d_1339,d_1340,d_1341,d_1342,d_1343,d_1344,d_1345,d_1346,d_1347,d_1348,d_1349,d_1350,d_1351,d_1352,d_1353,d_1354,d_1355,d_1356,d_1357,d_1358,d_1359,d_1360,d_1361,d_1362,d_1363,d_1364,d_1365,d_1366,d_1367,d_1368,d_1369,d_1370,d_1371,d_1372,d_1373,d_1374,d_1375,d_1376,d_1377,d_1378,d_1379,d_1380,d_1381,d_1382,d_1383,d_1384,d_1385,d_1386,d_1387,d_1388,d_1389,d_1390,d_1391,d_1392,d_1393,d_1394,d_1395,d_1396,d_1397,d_1398,d_1399,d_1400,d_1401,d_1402,d_1403,d_1404,d_1405,d_1406,d_1407,d_1408,d_1409,d_1410,d_1411,d_1412,d_1413,d_1414,d_1415,d_1416,d_1417,d_1418,d_1419,d_1420,d_1421,d_1422,d_1423,d_1424,d_1425,d_1426,d_1427,d_1428,d_1429,d_1430,d_1431,d_1432,d_1433,d_1434,d_1435,d_1436,d_1437,d_1438,d_1439,d_1440,d_1441,d_1442,d_1443,d_1444,d_1445,d_1446,d_1447,d_1448,d_1449,d_1450,d_1451,d_1452,d_1453,d_1454,d_1455,d_1456,d_1457,d_1458,d_1459,d_1460,d_1461,d_1462,d_1463,d_1464,d_1465,d_1466,d_1467,d_1468,d_1469,d_1470,d_1471,d_1472,d_1473,d_1474,d_1475,d_1476,d_1477,d_1478,d_1479,d_1480,d_1481,d_1482,d_1483,d_1484,d_1485,d_1486,d_1487,d_1488,d_1489,d_1490,d_1491,d_1492,d_1493,d_1494,d_1495,d_1496,d_1497,d_1498,d_1499,d_1500,d_1501,d_1502,d_1503,d_1504,d_1505,d_1506,d_1507,d_1508,d_1509,d_1510,d_1511,d_1512,d_1513,d_1514,d_1515,d_1516,d_1517,d_1518,d_1519,d_1520,d_1521,d_1522,d_1523,d_1524,d_1525,d_1526,d_1527,d_1528,d_1529,d_1530,d_1531,d_1532,d_1533,d_1534,d_1535,d_1536,d_1537,d_1538,d_1539,d_1540,d_1541,d_1542,d_1543,d_1544,d_1545,d_1546,d_1547,d_1548,d_1549,d_1550,d_1551,d_1552,d_1553,d_1554,d_1555,d_1556,d_1557,d_1558,d_1559,d_1560,d_1561,d_1562,d_1563,d_1564,d_1565,d_1566,d_1567,d_1568,d_1569,d_1570,d_1571,d_1572,d_1573,d_1574,d_1575,d_1576,d_1577,d_1578,d_1579,d_1580,d_1581,d_1582,d_1583,d_1584,d_1585,d_1586,d_1587,d_1588,d_1589,d_1590,d_1591,d_1592,d_1593,d_1594,d_1595,d_1596,d_1597,d_1598,d_1599,d_1600,d_1601,d_1602,d_1603,d_1604,d_1605,d_1606,d_1607,d_1608,d_1609,d_1610,d_1611,d_1612,d_1613,d_1614,d_1615,d_1616,d_1617,d_1618,d_1619,d_1620,d_1621,d_1622,d_1623,d_1624,d_1625,d_1626,d_1627,d_1628,d_1629,d_1630,d_1631,d_1632,d_1633,d_1634,d_1635,d_1636,d_1637,d_1638,d_1639,d_1640,d_1641,d_1642,d_1643,d_1644,d_1645,d_1646,d_1647,d_1648,d_1649,d_1650,d_1651,d_1652,d_1653,d_1654,d_1655,d_1656,d_1657,d_1658,d_1659,d_1660,d_1661,d_1662,d_1663,d_1664,d_1665,d_1666,d_1667,d_1668,d_1669,d_1670,d_1671,d_1672,d_1673,d_1674,d_1675,d_1676,d_1677,d_1678,d_1679,d_1680,d_1681,d_1682,d_1683,d_1684,d_1685,d_1686,d_1687,d_1688,d_1689,d_1690,d_1691,d_1692,d_1693,d_1694,d_1695,d_1696,d_1697,d_1698,d_1699,d_1700,d_1701,d_1702,d_1703,d_1704,d_1705,d_1706,d_1707,d_1708,d_1709,d_1710,d_1711,d_1712,d_1713,d_1714,d_1715,d_1716,d_1717,d_1718,d_1719,d_1720,d_1721,d_1722,d_1723,d_1724,d_1725,d_1726,d_1727,d_1728,d_1729,d_1730,d_1731,d_1732,d_1733,d_1734,d_1735,d_1736,d_1737,d_1738,d_1739,d_1740,d_1741,d_1742,d_1743,d_1744,d_1745,d_1746,d_1747,d_1748,d_1749,d_1750,d_1751,d_1752,d_1753,d_1754,d_1755,d_1756,d_1757,d_1758,d_1759,d_1760,d_1761,d_1762,d_1763,d_1764,d_1765,d_1766,d_1767,d_1768,d_1769,d_1770,d_1771,d_1772,d_1773,d_1774,d_1775,d_1776,d_1777,d_1778,d_1779,d_1780,d_1781,d_1782,d_1783,d_1784,d_1785,d_1786,d_1787,d_1788,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798,d_1799,d_1800,d_1801,d_1802,d_1803,d_1804,d_1805,d_1806,d_1807,d_1808,d_1809,d_1810,d_1811,d_1812,d_1813,d_1814,d_1815,d_1816,d_1817,d_1818,d_1819,d_1820,d_1821,d_1822,d_1823,d_1824,d_1825,d_1826,d_1827,d_1828,d_1829,d_1830,d_1831,d_1832,d_1833,d_1834,d_1835,d_1836,d_1837,d_1838,d_1839,d_1840,d_1841,d_1842,d_1843,d_1844,d_1845,d_1846,d_1847,d_1848,d_1849,d_1850,d_1851,d_1852,d_1853,d_1854,d_1855,d_1856,d_1857,d_1858,d_1859,d_1860,d_1861,d_1862,d_1863,d_1864,d_1865,d_1866,d_1867,d_1868,d_1869,d_1870,d_1871,d_1872,d_1873,d_1874,d_1875,d_1876,d_1877,d_1878,d_1879,d_1880,d_1881,d_1882,d_1883,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913,d_1914,d_1915,d_1916,d_1917,d_1918,d_1919,d_1920,d_1921,d_1922,d_1923,d_1924,d_1925,d_1926,d_1927,d_1928,d_1929,d_1930,d_1931,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,1,0,0,0,0,0,1,2,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,2,1,0,0,0,2,0,0,0,0,0,1,0,0,0,1,0,1,2,1,1,0,0,0,0,1,0,0,1,2,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,2,2,0,1,1,0,0,0,1,1,0,1,1,1,1,0,2,3,1,1,0,0,0,0,0,1,0,0,0,0,2,1,0,0,1,1,2,1,1,0,1,0,1,1,0,1,1,0,3,0,0,3,0,1,1,2,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,2,0,0,1,0,2,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,2,0,0,0,0,0,0,1,2,0,0,0,2,1,2,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,1,1,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,2,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,2,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0,1,1,2,0,1,0,0,0,0,0,0,0,0,3,1,2,2,1,1,0,0,2,0,0,0,0,1,0,1,0,0,0,1,1,0,3,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0,2,0,0,2,0,0,0,1,0,0,0,0,0,4,0,0,2,1,0,0,0,0,0,1,0,0,0,0,0,4,0,1,0,1,2,2,0,0,0,0,2,1,1,1,1,1,0,0,1,0,0,1,0,0,0,1,1,0,1,2,0,0,2,0,1,3,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,1,0,1,1,0,0,1,1,1,0,0,0,0,0,2,0,0,0,0,3,0,2,0,0,0,0,3,2,0,2,0,0,2,0,0,0,0,3,0,1,1,1,0,1,0,1,0,0,2,4,0,0,0,0,0,2,0,0,1,0,0,1,1,5,1,1,0,0,0,0,0,0,0,0,2,1,1,0,2,0,2,1,0,1,0,1,1,0,0,0,2,1,1,0,0,1,0,3,0,0,0,1,0,0,2,1,0,1,0,0,3,3,0,0,0,0,0,0,0,1,1,1,0,2,2,2,0,0,1,0,0,1,3,0,0,0,1,1,0,1,0,1,0,0,1,1,1,2,1,1,1,0,2,2,2,1,0,0,0,1,2,0,0,1,2,1,1,1,0,1,0,1,0,0,1,0,1,0,2,1,0,2,0,1,0,0,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,3,1,1,0,1,1,0,0,0,1,1,2,0,0,0,1,0,2,1,0,1,1,0,0,0,1,1,1,3,1,1,0,0,2,0,1,0,0,0,2,0,0,0,4,2,1,0,0,0,0,2,1,0,1,1,0,0,0,1,2,1,1,0,0,2,0,2,2,0,0,0,1,1,0,2,0,1,1,2,0,1,0,0,0,2,1,0,1,1,2,0,0,0,0,0,0,0,1,0,1,0,1,0,3,1,1,0,1,1,2,0,0,0,0,1,1,0,0,0,0,3,0,1,0,0,0,0,1,1,1,0,1,0,2,0,0,0,0,2,0,0,0,0,1,1,2,0,0,0,0,2,0,0,1,1,1,1,0,0,0,0,0,1,2,2,0,1,0,0,0,0,1,2,1,0,0,0,0,0,1,0,3,0,1,2,1,0,3,0,0,0,1,0,2,2,1,0,0,1,2,0,1,0,1,4,0,0,5,0,0,0,0,0,0,2,1,2,1,0,0,0,1,1,1,0,0,1,1,1,1,1,0,0,0,2,2,0,0,1,4,0,0,0,0,1,1,2,0,4,0,1,0,1,4,2,0,2,0,1,1,0,1,0,0,1,1,3,0,0,0,1,1,1,3,1,3,1,2,2,0,1,1,1,1,0,0,0,0,0,1,0,4,2,3,0,1,2,0,0,0,1,1,3,0,1,1,1,3,0,1,1,0,0,0,2,0,3,5,0,0,1,1,0,2,1,2,2,1,0,2,4,0,0,0,0,3,3,0,1

In [38]:
sales.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Data columns (total 1947 columns):
 #     Column    Dtype
---    ------    -----
 0     id        str
 1     item_id   str
 2     dept_id   str
 3     cat_id    str
 4     store_id  str
 5     state_id  str
 6     d_1       int64
 7     d_2       int64
 8     d_3       int64
 9     d_4       int64
 10    d_5       int64
 11    d_6       int64
 12    d_7       int64
 13    d_8       int64
 14    d_9       int64
 15    d_10      int64
 16    d_11      int64
 17    d_12      int64
 18    d_13      int64
 19    d_14      int64
 20    d_15      int64
 21    d_16      int64
 22    d_17      int64
 23    d_18      int64
 24    d_19      int64
 25    d_20      int64
 26    d_21      int64
 27    d_22      int64
 28    d_23      int64
 29    d_24      int64
 30    d_25      int64
 31    d_26      int64
 32    d_27      int64
 33    d_28      int64
 34    d_29      int64
 35    d_30      int64
 36    d_31      int64
 37    d_32      int64
 38    d_33      int64
 39    d_34      int64
 40    d_35      int64
 41    d_36      int64
 42    d_37      int64
 43    d_38      int64
 44    d_39      int64
 45    d_40      int64
 46    d_41      int64
 47    d_42      int64
 48    d_43      int64
 49    d_44      int64
 50    d_45      int64
 51    d_46      int64
 52    d_47      int64
 53    d_48      int64
 54    d_49      int64
 55    d_50      int64
 56    d_51      int64
 57    d_52      int64
 58    d_53      int64
 59    d_54      int64
 60    d_55      int64
 61    d_56      int64
 62    d_57      int64
 63    d_58      int64
 64    d_59      int64
 65    d_60      int64
 66    d_61      int64
 67    d_62      int64
 68    d_63      int64
 69    d_64      int64
 70    d_65      int64
 71    d_66      int64
 72    d_67      int64
 73    d_68      int64
 74    d_69      int64
 75    d_70      int64
 76    d_71      int64
 77    d_72      int64
 78    d_73      int64
 79    d_74      int64
 80    d_75      int64
 81    d_76      int64
 82    d_77      int64
 83    d_78      int64
 84    d_79      int64
 85    d_80      int64
 86    d_81      int64
 87    d_82      int64
 88    d_83      int64
 89    d_84      int64
 90    d_85      int64
 91    d_86      int64
 92    d_87      int64
 93    d_88      int64
 94    d_89      int64
 95    d_90      int64
 96    d_91      int64
 97    d_92      int64
 98    d_93      int64
 99    d_94      int64
 100   d_95      int64
 101   d_96      int64
 102   d_97      int64
 103   d_98      int64
 104   d_99      int64
 105   d_100     int64
 106   d_101     int64
 107   d_102     int64
 108   d_103     int64
 109   d_104     int64
 110   d_105     int64
 111   d_106     int64
 112   d_107     int64
 113   d_108     int64
 114   d_109     int64
 115   d_110     int64
 116   d_111     int64
 117   d_112     int64
 118   d_113     int64
 119   d_114     int64
 120   d_115     int64
 121   d_116     int64
 122   d_117     int64
 123   d_118     int64
 124   d_119     int64
 125   d_120     int64
 126   d_121     int64
 127   d_122     int64
 128   d_123     int64
 129   d_124     int64
 130   d_125     int64
 131   d_126     int64
 132   d_127     int64
 133   d_128     int64
 134   d_129     int64
 135   d_130     int64
 136   d_131     int64
 137   d_132     int64
 138   d_133     int64
 139   d_134     int64
 140   d_135     int64
 141   d_136     int64
 142   d_137     int64
 143   d_138     int64
 144   d_139     int64
 145   d_140     int64
 146   d_141     int64
 147   d_142     int64
 148   d_143     int64
 149   d_144     int64
 150   d_145     int64
 151   d_146     int64
 152   d_147     int64
 153   d_148     int64
 154   d_149     int64
 155   d_150     int64
 156   d_151     int64
 157   d_152     int64
 158   d_153     int64
 159   d_154     int64
 160   d_155     int64
 161   d_156     int64
 162   d_157     int64
 163   d_158     int64
 164   d_159     int64
 165   d_160     int64
 166   d_161     int64
 167   d_162     int64
 168   d_163     int64
 169   d_164     int64
 170   d_165     int64
 171   d_166     int64
 172   d_167     int64
 173   d_168     int64
 174   d_169     int64
 175   d_170     int64
 176   d_171     int64
 177   d_172     int64
 178   d_173     int64
 179   d_174     int64
 180   d_175     int64
 181   d_176     int64
 182   d_177     int64
 183   d_178     int64
 184   d_179     int64
 185   d_180     int64
 186   d_181     int64
 187   d_182     int64
 188   d_183     int64
 189   d_184     int64
 190   d_185     int64
 191   d_186     int64
 192   d_187     int64
 193   d_188     int64
 194   d_189     int64
 195   d_190     int64
 196   d_191     int64
 197   d_192     int64
 198   d_193     int64
 199   d_194     int64
 200   d_195     int64
 201   d_196     int64
 202   d_197     int64
 203   d_198     int64
 204   d_199     int64
 205   d_200     int64
 206   d_201     int64
 207   d_202     int64
 208   d_203     int64
 209   d_204     int64
 210   d_205     int64
 211   d_206     int64
 212   d_207     int64
 213   d_208     int64
 214   d_209     int64
 215   d_210     int64
 216   d_211     int64
 217   d_212     int64
 218   d_213     int64
 219   d_214     int64
 220   d_215     int64
 221   d_216     int64
 222   d_217     int64
 223   d_218     int64
 224   d_219     int64
 225   d_220     int64
 226   d_221     int64
 227   d_222     int64
 228   d_223     int64
 229   d_224     int64
 230   d_225     int64
 231   d_226     int64
 232   d_227     int64
 233   d_228     int64
 234   d_229     int64
 235   d_230     int64
 236   d_231     int64
 237   d_232     int64
 238   d_233     int64
 239   d_234     int64
 240   d_235     int64
 241   d_236     int64
 242   d_237     int64
 243   d_238     int64
 244   d_239     int64
 245   d_240     int64
 246   d_241     int64
 247   d_242     int64
 248   d_243     int64
 249   d_244     int64
 250   d_245     int64
 251   d_246     int64
 252   d_247     int64
 253   d_248     int64
 254   d_249     int64
 255   d_250     int64
 256   d_251     int64
 257   d_252     int64
 258   d_253     int64
 259   d_254     int64
 260   d_255     int64
 261   d_256     int64
 262   d_257     int64
 263   d_258     int64
 264   d_259     int64
 265   d_260     int64
 266   d_261     int64
 267   d_262     int64
 268   d_263     int64
 269   d_264     int64
 270   d_265     int64
 271   d_266     int64
 272   d_267     int64
 273   d_268     int64
 274   d_269     int64
 275   d_270     int64
 276   d_271     int64
 277   d_272     int64
 278   d_273     int64
 279   d_274     int64
 280   d_275     int64
 281   d_276     int64
 282   d_277     int64
 283   d_278     int64
 284   d_279     int64
 285   d_280     int64
 286   d_281     int64
 287   d_282     int64
 288   d_283     int64
 289   d_284     int64
 290   d_285     int64
 291   d_286     int64
 292   d_287     int64
 293   d_288     int64
 294   d_289     int64
 295   d_290     int64
 296   d_291     int64
 297   d_292     int64
 298   d_293     int64
 299   d_294     int64
 300   d_295     int64
 301   d_296     int64
 302   d_297     int64
 303   d_298     int64
 304   d_299     int64
 305   d_300     int64
 306   d_301     int64
 307   d_302     int64
 308   d_303     int64
 309   d_304     int64
 310   d_305     int64
 311   d_306     int64
 312   d_307     int64
 313   d_308     int64
 314   d_309     int64
 315   d_310     int64
 316   d_311     int64
 317   d_312     int64
 318   d_313     int64
 319   d_314     int64
 320   d_315     int64
 321   d_316     int64
 322   d_317     int64
 323   d_318     int64
 324   d_319     int64
 325   d_320     int64
 326   d_321     int64
 327   d_322     int64
 328   d_323     int64
 329   d_324     int64
 330   d_325     int64
 331   d_326     int64
 332   d_327     int64
 333   d_328     int64
 334   d_329     int64
 335   d_330     int64
 336   d_331     int64
 337   d_332     int64
 338   d_333     int64
 339   d_334     int64
 340   d_335     int64
 341   d_336     int64
 342   d_337     int64
 343   d_338     int64
 344   d_339     int64
 345   d_340     int64
 346   d_341     int64
 347   d_342     int64
 348   d_343     int64
 349   d_344     int64
 350   d_345     int64
 351   d_346     int64
 352   d_347     int64
 353   d_348     int64
 354   d_349     int64
 355   d_350     int64
 356   d_351     int64
 357   d_352     int64
 358   d_353     int64
 359   d_354     int64
 360   d_355     int64
 361   d_356     int64
 362   d_357     int64
 363   d_358     int64
 364   d_359     int64
 365   d_360     int64
 366   d_361     int64
 367   d_362     int64
 368   d_363     int64
 369   d_364     int64
 370   d_365     int64
 371   d_366     int64
 372   d_367     int64
 373   d_368     int64
 374   d_369     int64
 375   d_370     int64
 376   d_371     int64
 377   d_372     int64
 378   d_373     int64
 379   d_374     int64
 380   d_375     int64
 381   d_376     int64
 382   d_377     int64
 383   d_378     int64
 384   d_379     int64
 385   d_380     int64
 386   d_381     int64
 387   d_382     int64
 388   d_383     int64
 389   d_384     int64
 390   d_385     int64
 391   d_386     int64
 392   d_387     int64
 393   d_388     int64
 394   d_389     int64
 395   d_390     int64
 396   d_391     int64
 397   d_392     int64
 398   d_393     int64
 399   d_394     int64
 400   d_395     int64
 401   d_396     int64
 402   d_397     int64
 403   d_398     int64
 404   d_399     int64
 405   d_400     int64
 406   d_401     int64
 407   d_402     int64
 408   d_403     int64
 409   d_404     int64
 410   d_405     int64
 411   d_406     int64
 412   d_407     int64
 413   d_408     int64
 414   d_409     int64
 415   d_410     int64
 416   d_411     int64
 417   d_412     int64
 418   d_413     int64
 419   d_414     int64
 420   d_415     int64
 421   d_416     int64
 422   d_417     int64
 423   d_418     int64
 424   d_419     int64
 425   d_420     int64
 426   d_421     int64
 427   d_422     int64
 428   d_423     int64
 429   d_424     int64
 430   d_425     int64
 431   d_426     int64
 432   d_427     int64
 433   d_428     int64
 434   d_429     int64
 435   d_430     int64
 436   d_431     int64
 437   d_432     int64
 438   d_433     int64
 439   d_434     int64
 440   d_435     int64
 441   d_436     int64
 442   d_437     int64
 443   d_438     int64
 444   d_439     int64
 445   d_440     int64
 446   d_441     int64
 447   d_442     int64
 448   d_443     int64
 449   d_444     int64
 450   d_445     int64
 451   d_446     int64
 452   d_447     int64
 453   d_448     int64
 454   d_449     int64
 455   d_450     int64
 456   d_451     int64
 457   d_452     int64
 458   d_453     int64
 459   d_454     int64
 460   d_455     int64
 461   d_456     int64
 462   d_457     int64
 463   d_458     int64
 464   d_459     int64
 465   d_460     int64
 466   d_461     int64
 467   d_462     int64
 468   d_463     int64
 469   d_464     int64
 470   d_465     int64
 471   d_466     int64
 472   d_467     int64
 473   d_468     int64
 474   d_469     int64
 475   d_470     int64
 476   d_471     int64
 477   d_472     int64
 478   d_473     int64
 479   d_474     int64
 480   d_475     int64
 481   d_476     int64
 482   d_477     int64
 483   d_478     int64
 484   d_479     int64
 485   d_480     int64
 486   d_481     int64
 487   d_482     int64
 488   d_483     int64
 489   d_484     int64
 490   d_485     int64
 491   d_486     int64
 492   d_487     int64
 493   d_488     int64
 494   d_489     int64
 495   d_490     int64
 496   d_491     int64
 497   d_492     int64
 498   d_493     int64
 499   d_494     int64
 500   d_495     int64
 501   d_496     int64
 502   d_497     int64
 503   d_498     int64
 504   d_499     int64
 505   d_500     int64
 506   d_501     int64
 507   d_502     int64
 508   d_503     int64
 509   d_504     int64
 510   d_505     int64
 511   d_506     int64
 512   d_507     int64
 513   d_508     int64
 514   d_509     int64
 515   d_510     int64
 516   d_511     int64
 517   d_512     int64
 518   d_513     int64
 519   d_514     int64
 520   d_515     int64
 521   d_516     int64
 522   d_517     int64
 523   d_518     int64
 524   d_519     int64
 525   d_520     int64
 526   d_521     int64
 527   d_522     int64
 528   d_523     int64
 529   d_524     int64
 530   d_525     int64
 531   d_526     int64
 532   d_527     int64
 533   d_528     int64
 534   d_529     int64
 535   d_530     int64
 536   d_531     int64
 537   d_532     int64
 538   d_533     int64
 539   d_534     int64
 540   d_535     int64
 541   d_536     int64
 542   d_537     int64
 543   d_538     int64
 544   d_539     int64
 545   d_540     int64
 546   d_541     int64
 547   d_542     int64
 548   d_543     int64
 549   d_544     int64
 550   d_545     int64
 551   d_546     int64
 552   d_547     int64
 553   d_548     int64
 554   d_549     int64
 555   d_550     int64
 556   d_551     int64
 557   d_552     int64
 558   d_553     int64
 559   d_554     int64
 560   d_555     int64
 561   d_556     int64
 562   d_557     int64
 563   d_558     int64
 564   d_559     int64
 565   d_560     int64
 566   d_561     int64
 567   d_562     int64
 568   d_563     int64
 569   d_564     int64
 570   d_565     int64
 571   d_566     int64
 572   d_567     int64
 573   d_568     int64
 574   d_569     int64
 575   d_570     int64
 576   d_571     int64
 577   d_572     int64
 578   d_573     int64
 579   d_574     int64
 580   d_575     int64
 581   d_576     int64
 582   d_577     int64
 583   d_578     int64
 584   d_579     int64
 585   d_580     int64
 586   d_581     int64
 587   d_582     int64
 588   d_583     int64
 589   d_584     int64
 590   d_585     int64
 591   d_586     int64
 592   d_587     int64
 593   d_588     int64
 594   d_589     int64
 595   d_590     int64
 596   d_591     int64
 597   d_592     int64
 598   d_593     int64
 599   d_594     int64
 600   d_595     int64
 601   d_596     int64
 602   d_597     int64
 603   d_598     int64
 604   d_599     int64
 605   d_600     int64
 606   d_601     int64
 607   d_602     int64
 608   d_603     int64
 609   d_604     int64
 610   d_605     int64
 611   d_606     int64
 612   d_607     int64
 613   d_608     int64
 614   d_609     int64
 615   d_610     int64
 616   d_611     int64
 617   d_612     int64
 618   d_613     int64
 619   d_614     int64
 620   d_615     int64
 621   d_616     int64
 622   d_617     int64
 623   d_618     int64
 624   d_619     int64
 625   d_620     int64
 626   d_621     int64
 627   d_622     int64
 628   d_623     int64
 629   d_624     int64
 630   d_625     int64
 631   d_626     int64
 632   d_627     int64
 633   d_628     int64
 634   d_629     int64
 635   d_630     int64
 636   d_631     int64
 637   d_632     int64
 638   d_633     int64
 639   d_634     int64
 640   d_635     int64
 641   d_636     int64
 642   d_637     int64
 643   d_638     int64
 644   d_639     int64
 645   d_640     int64
 646   d_641     int64
 647   d_642     int64
 648   d_643     int64
 649   d_644     int64
 650   d_645     int64
 651   d_646     int64
 652   d_647     int64
 653   d_648     int64
 654   d_649     int64
 655   d_650     int64
 656   d_651     int64
 657   d_652     int64
 658   d_653     int64
 659   d_654     int64
 660   d_655     int64
 661   d_656     int64
 662   d_657     int64
 663   d_658     int64
 664   d_659     int64
 665   d_660     int64
 666   d_661     int64
 667   d_662     int64
 668   d_663     int64
 669   d_664     int64
 670   d_665     int64
 671   d_666     int64
 672   d_667     int64
 673   d_668     int64
 674   d_669     int64
 675   d_670     int64
 676   d_671     int64
 677   d_672     int64
 678   d_673     int64
 679   d_674     int64
 680   d_675     int64
 681   d_676     int64
 682   d_677     int64
 683   d_678     int64
 684   d_679     int64
 685   d_680     int64
 686   d_681     int64
 687   d_682     int64
 688   d_683     int64
 689   d_684     int64
 690   d_685     int64
 691   d_686     int64
 692   d_687     int64
 693   d_688     int64
 694   d_689     int64
 695   d_690     int64
 696   d_691     int64
 697   d_692     int64
 698   d_693     int64
 699   d_694     int64
 700   d_695     int64
 701   d_696     int64
 702   d_697     int64
 703   d_698     int64
 704   d_699     int64
 705   d_700     int64
 706   d_701     int64
 707   d_702     int64
 708   d_703     int64
 709   d_704     int64
 710   d_705     int64
 711   d_706     int64
 712   d_707     int64
 713   d_708     int64
 714   d_709     int64
 715   d_710     int64
 716   d_711     int64
 717   d_712     int64
 718   d_713     int64
 719   d_714     int64
 720   d_715     int64
 721   d_716     int64
 722   d_717     int64
 723   d_718     int64
 724   d_719     int64
 725   d_720     int64
 726   d_721     int64
 727   d_722     int64
 728   d_723     int64
 729   d_724     int64
 730   d_725     int64
 731   d_726     int64
 732   d_727     int64
 733   d_728     int64
 734   d_729     int64
 735   d_730     int64
 736   d_731     int64
 737   d_732     int64
 738   d_733     int64
 739   d_734     int64
 740   d_735     int64
 741   d_736     int64
 742   d_737     int64
 743   d_738     int64
 744   d_739     int64
 745   d_740     int64
 746   d_741     int64
 747   d_742     int64
 748   d_743     int64
 749   d_744     int64
 750   d_745     int64
 751   d_746     int64
 752   d_747     int64
 753   d_748     int64
 754   d_749     int64
 755   d_750     int64
 756   d_751     int64
 757   d_752     int64
 758   d_753     int64
 759   d_754     int64
 760   d_755     int64
 761   d_756     int64
 762   d_757     int64
 763   d_758     int64
 764   d_759     int64
 765   d_760     int64
 766   d_761     int64
 767   d_762     int64
 768   d_763     int64
 769   d_764     int64
 770   d_765     int64
 771   d_766     int64
 772   d_767     int64
 773   d_768     int64
 774   d_769     int64
 775   d_770     int64
 776   d_771     int64
 777   d_772     int64
 778   d_773     int64
 779   d_774     int64
 780   d_775     int64
 781   d_776     int64
 782   d_777     int64
 783   d_778     int64
 784   d_779     int64
 785   d_780     int64
 786   d_781     int64
 787   d_782     int64
 788   d_783     int64
 789   d_784     int64
 790   d_785     int64
 791   d_786     int64
 792   d_787     int64
 793   d_788     int64
 794   d_789     int64
 795   d_790     int64
 796   d_791     int64
 797   d_792     int64
 798   d_793     int64
 799   d_794     int64
 800   d_795     int64
 801   d_796     int64
 802   d_797     int64
 803   d_798     int64
 804   d_799     int64
 805   d_800     int64
 806   d_801     int64
 807   d_802     int64
 808   d_803     int64
 809   d_804     int64
 810   d_805     int64
 811   d_806     int64
 812   d_807     int64
 813   d_808     int64
 814   d_809     int64
 815   d_810     int64
 816   d_811     int64
 817   d_812     int64
 818   d_813     int64
 819   d_814     int64
 820   d_815     int64
 821   d_816     int64
 822   d_817     int64
 823   d_818     int64
 824   d_819     int64
 825   d_820     int64
 826   d_821     int64
 827   d_822     int64
 828   d_823     int64
 829   d_824     int64
 830   d_825     int64
 831   d_826     int64
 832   d_827     int64
 833   d_828     int64
 834   d_829     int64
 835   d_830     int64
 836   d_831     int64
 837   d_832     int64
 838   d_833     int64
 839   d_834     int64
 840   d_835     int64
 841   d_836     int64
 842   d_837     int64
 843   d_838     int64
 844   d_839     int64
 845   d_840     int64
 846   d_841     int64
 847   d_842     int64
 848   d_843     int64
 849   d_844     int64
 850   d_845     int64
 851   d_846     int64
 852   d_847     int64
 853   d_848     int64
 854   d_849     int64
 855   d_850     int64
 856   d_851     int64
 857   d_852     int64
 858   d_853     int64
 859   d_854     int64
 860   d_855     int64
 861   d_856     int64
 862   d_857     int64

In [39]:
sales['id'].sample(10)

4304     HOUSEHOLD_2_159_CA_2_evaluation
4679         FOODS_1_020_CA_2_evaluation
27293        FOODS_3_677_WI_2_evaluation
16601    HOUSEHOLD_2_261_TX_2_evaluation
16615    HOUSEHOLD_2_275_TX_2_evaluation
20673        FOODS_3_155_TX_3_evaluation
15848    HOUSEHOLD_1_040_TX_2_evaluation
19678    HOUSEHOLD_2_289_TX_3_evaluation
22123    HOUSEHOLD_1_220_WI_1_evaluation
7730         FOODS_1_022_CA_3_evaluation
Name: id, dtype: str

In [40]:
sales['item_id'].head(1)

0    HOBBIES_1_001
Name: item_id, dtype: str

In [41]:
sales['dept_id'].value_counts()

dept_id
FOODS_3        8230
HOUSEHOLD_1    5320
HOUSEHOLD_2    5150
HOBBIES_1      4160
FOODS_2        3980
FOODS_1        2160
HOBBIES_2      1490
Name: count, dtype: int64

In [42]:
sales['cat_id'].value_counts()

cat_id
FOODS        14370
HOUSEHOLD    10470
HOBBIES       5650
Name: count, dtype: int64

In [43]:
sales['store_id'].value_counts()

store_id
CA_1    3049
CA_2    3049
CA_3    3049
CA_4    3049
TX_1    3049
TX_2    3049
TX_3    3049
WI_1    3049
WI_2    3049
WI_3    3049
Name: count, dtype: int64

In [44]:
sales['state_id'].value_counts()

state_id
CA    12196
TX     9147
WI     9147
Name: count, dtype: int64

In [45]:
sales.sample(10)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,d_26,d_27,d_28,d_29,d_30,d_31,d_32,d_33,d_34,d_35,d_36,d_37,d_38,d_39,d_40,d_41,d_42,d_43,d_44,d_45,d_46,d_47,d_48,d_49,d_50,d_51,d_52,d_53,d_54,d_55,d_56,d_57,d_58,d_59,d_60,d_61,d_62,d_63,d_64,d_65,d_66,d_67,d_68,d_69,d_70,d_71,d_72,d_73,d_74,d_75,d_76,d_77,d_78,d_79,d_80,d_81,d_82,d_83,d_84,d_85,d_86,d_87,d_88,d_89,d_90,d_91,d_92,d_93,d_94,d_95,d_96,d_97,d_98,d_99,d_100,d_101,d_102,d_103,d_104,d_105,d_106,d_107,d_108,d_109,d_110,d_111,d_112,d_113,d_114,d_115,d_116,d_117,d_118,d_119,d_120,d_121,d_122,d_123,d_124,d_125,d_126,d_127,d_128,d_129,d_130,d_131,d_132,d_133,d_134,d_135,d_136,d_137,d_138,d_139,d_140,d_141,d_142,d_143,d_144,d_145,d_146,d_147,d_148,d_149,d_150,d_151,d_152,d_153,d_154,d_155,d_156,d_157,d_158,d_159,d_160,d_161,d_162,d_163,d_164,d_165,d_166,d_167,d_168,d_169,d_170,d_171,d_172,d_173,d_174,d_175,d_176,d_177,d_178,d_179,d_180,d_181,d_182,d_183,d_184,d_185,d_186,d_187,d_188,d_189,d_190,d_191,d_192,d_193,d_194,d_195,d_196,d_197,d_198,d_199,d_200,d_201,d_202,d_203,d_204,d_205,d_206,d_207,d_208,d_209,d_210,d_211,d_212,d_213,d_214,d_215,d_216,d_217,d_218,d_219,d_220,d_221,d_222,d_223,d_224,d_225,d_226,d_227,d_228,d_229,d_230,d_231,d_232,d_233,d_234,d_235,d_236,d_237,d_238,d_239,d_240,d_241,d_242,d_243,d_244,d_245,d_246,d_247,d_248,d_249,d_250,d_251,d_252,d_253,d_254,d_255,d_256,d_257,d_258,d_259,d_260,d_261,d_262,d_263,d_264,d_265,d_266,d_267,d_268,d_269,d_270,d_271,d_272,d_273,d_274,d_275,d_276,d_277,d_278,d_279,d_280,d_281,d_282,d_283,d_284,d_285,d_286,d_287,d_288,d_289,d_290,d_291,d_292,d_293,d_294,d_295,d_296,d_297,d_298,d_299,d_300,d_301,d_302,d_303,d_304,d_305,d_306,d_307,d_308,d_309,d_310,d_311,d_312,d_313,d_314,d_315,d_316,d_317,d_318,d_319,d_320,d_321,d_322,d_323,d_324,d_325,d_326,d_327,d_328,d_329,d_330,d_331,d_332,d_333,d_334,d_335,d_336,d_337,d_338,d_339,d_340,d_341,d_342,d_343,d_344,d_345,d_346,d_347,d_348,d_349,d_350,d_351,d_352,d_353,d_354,d_355,d_356,d_357,d_358,d_359,d_360,d_361,d_362,d_363,d_364,d_365,d_366,d_367,d_368,d_369,d_370,d_371,d_372,d_373,d_374,d_375,d_376,d_377,d_378,d_379,d_380,d_381,d_382,d_383,d_384,d_385,d_386,d_387,d_388,d_389,d_390,d_391,d_392,d_393,d_394,d_395,d_396,d_397,d_398,d_399,d_400,d_401,d_402,d_403,d_404,d_405,d_406,d_407,d_408,d_409,d_410,d_411,d_412,d_413,d_414,d_415,d_416,d_417,d_418,d_419,d_420,d_421,d_422,d_423,d_424,d_425,d_426,d_427,d_428,d_429,d_430,d_431,d_432,d_433,d_434,d_435,d_436,d_437,d_438,d_439,d_440,d_441,d_442,d_443,d_444,d_445,d_446,d_447,d_448,d_449,d_450,d_451,d_452,d_453,d_454,d_455,d_456,d_457,d_458,d_459,d_460,d_461,d_462,d_463,d_464,d_465,d_466,d_467,d_468,d_469,d_470,d_471,d_472,d_473,d_474,d_475,d_476,d_477,d_478,d_479,d_480,d_481,d_482,d_483,d_484,d_485,d_486,d_487,d_488,d_489,d_490,d_491,d_492,d_493,d_494,d_495,d_496,d_497,d_498,d_499,d_500,d_501,d_502,d_503,d_504,d_505,d_506,d_507,d_508,d_509,d_510,d_511,d_512,d_513,d_514,d_515,d_516,d_517,d_518,d_519,d_520,d_521,d_522,d_523,d_524,d_525,d_526,d_527,d_528,d_529,d_530,d_531,d_532,d_533,d_534,d_535,d_536,d_537,d_538,d_539,d_540,d_541,d_542,d_543,d_544,d_545,d_546,d_547,d_548,d_549,d_550,d_551,d_552,d_553,d_554,d_555,d_556,d_557,d_558,d_559,d_560,d_561,d_562,d_563,d_564,d_565,d_566,d_567,d_568,d_569,d_570,d_571,d_572,d_573,d_574,d_575,d_576,d_577,d_578,d_579,d_580,d_581,d_582,d_583,d_584,d_585,d_586,d_587,d_588,d_589,d_590,d_591,d_592,d_593,d_594,d_595,d_596,d_597,d_598,d_599,d_600,d_601,d_602,d_603,d_604,d_605,d_606,d_607,d_608,d_609,d_610,d_611,d_612,d_613,d_614,d_615,d_616,d_617,d_618,d_619,d_620,d_621,d_622,d_623,d_624,d_625,d_626,d_627,d_628,d_629,d_630,d_631,d_632,d_633,d_634,d_635,d_636,d_637,d_638,d_639,d_640,d_641,d_642,d_643,d_644,d_645,d_646,d_647,d_648,d_649,d_650,d_651,d_652,d_653,d_654,d_655,d_656,d_657,d_658,d_659,d_660,d_661,d_662,d_663,d_664,d_665,d_666,d_667,d_668,d_669,d_670,d_671,d_672,d_673,d_674,d_675,d_676,d_677,d_678,d_679,d_680,d_681,d_682,d_683,d_684,d_685,d_686,d_687,d_688,d_689,d_690,d_691,d_692,d_693,d_694,d_695,d_696,d_697,d_698,d_699,d_700,d_701,d_702,d_703,d_704,d_705,d_706,d_707,d_708,d_709,d_710,d_711,d_712,d_713,d_714,d_715,d_716,d_717,d_718,d_719,d_720,d_721,d_722,d_723,d_724,d_725,d_726,d_727,d_728,d_729,d_730,d_731,d_732,d_733,d_734,d_735,d_736,d_737,d_738,d_739,d_740,d_741,d_742,d_743,d_744,d_745,d_746,d_747,d_748,d_749,d_750,d_751,d_752,d_753,d_754,d_755,d_756,d_757,d_758,d_759,d_760,d_761,d_762,d_763,d_764,d_765,d_766,d_767,d_768,d_769,d_770,d_771,d_772,d_773,d_774,d_775,d_776,d_777,d_778,d_779,d_780,d_781,d_782,d_783,d_784,d_785,d_786,d_787,d_788,d_789,d_790,d_791,d_792,d_793,d_794,d_795,d_796,d_797,d_798,d_799,d_800,d_801,d_802,d_803,d_804,d_805,d_806,d_807,d_808,d_809,d_810,d_811,d_812,d_813,d_814,d_815,d_816,d_817,d_818,d_819,d_820,d_821,d_822,d_823,d_824,d_825,d_826,d_827,d_828,d_829,d_830,d_831,d_832,d_833,d_834,d_835,d_836,d_837,d_838,d_839,d_840,d_841,d_842,d_843,d_844,d_845,d_846,d_847,d_848,d_849,d_850,d_851,d_852,d_853,d_854,d_855,d_856,d_857,d_858,d_859,d_860,d_861,d_862,d_863,d_864,d_865,d_866,d_867,d_868,d_869,d_870,d_871,d_872,d_873,d_874,d_875,d_876,d_877,d_878,d_879,d_880,d_881,d_882,d_883,d_884,d_885,d_886,d_887,d_888,d_889,d_890,d_891,d_892,d_893,d_894,d_895,d_896,d_897,d_898,d_899,d_900,d_901,d_902,d_903,d_904,d_905,d_906,d_907,d_908,d_909,d_910,d_911,d_912,d_913,d_914,d_915,d_916,d_917,d_918,d_919,d_920,d_921,d_922,d_923,d_924,d_925,d_926,d_927,d_928,d_929,d_930,d_931,d_932,d_933,d_934,d_935,d_936,d_937,d_938,d_939,d_940,d_941,d_942,d_943,d_944,d_945,d_946,d_947,d_948,d_949,d_950,d_951,d_952,d_953,d_954,d_955,d_956,d_957,d_958,d_959,d_960,d_961,d_962,d_963,d_964,d_965,d_966,d_967,d_968,d_969,d_970,d_971,d_972,d_973,d_974,d_975,d_976,d_977,d_978,d_979,d_980,d_981,d_982,d_983,d_984,d_985,d_986,d_987,d_988,d_989,d_990,d_991,d_992,d_993,d_994,d_995,d_996,d_997,d_998,d_999,d_1000,d_1001,d_1002,d_1003,d_1004,d_1005,d_1006,d_1007,d_1008,d_1009,d_1010,d_1011,d_1012,d_1013,d_1014,d_1015,d_1016,d_1017,d_1018,d_1019,d_1020,d_1021,d_1022,d_1023,d_1024,d_1025,d_1026,d_1027,d_1028,d_1029,d_1030,d_1031,d_1032,d_1033,d_1034,d_1035,d_1036,d_1037,d_1038,d_1039,d_1040,d_1041,d_1042,d_1043,d_1044,d_1045,d_1046,d_1047,d_1048,d_1049,d_1050,d_1051,d_1052,d_1053,d_1054,d_1055,d_1056,d_1057,d_1058,d_1059,d_1060,d_1061,d_1062,d_1063,d_1064,d_1065,d_1066,d_1067,d_1068,d_1069,d_1070,d_1071,d_1072,d_1073,d_1074,d_1075,d_1076,d_1077,d_1078,d_1079,d_1080,d_1081,d_1082,d_1083,d_1084,d_1085,d_1086,d_1087,d_1088,d_1089,d_1090,d_1091,d_1092,d_1093,d_1094,d_1095,d_1096,d_1097,d_1098,d_1099,d_1100,d_1101,d_1102,d_1103,d_1104,d_1105,d_1106,d_1107,d_1108,d_1109,d_1110,d_1111,d_1112,d_1113,d_1114,d_1115,d_1116,d_1117,d_1118,d_1119,d_1120,d_1121,d_1122,d_1123,d_1124,d_1125,d_1126,d_1127,d_1128,d_1129,d_1130,d_1131,d_1132,d_1133,d_1134,d_1135,d_1136,d_1137,d_1138,d_1139,d_1140,d_1141,d_1142,d_1143,d_1144,d_1145,d_1146,d_1147,d_1148,d_1149,d_1150,d_1151,d_1152,d_1153,d_1154,d_1155,d_1156,d_1157,d_1158,d_1159,d_1160,d_1161,d_1162,d_1163,d_1164,d_1165,d_1166,d_1167,d_1168,d_1169,d_1170,d_1171,d_1172,d_1173,d_1174,d_1175,d_1176,d_1177,d_1178,d_1179,d_1180,d_1181,d_1182,d_1183,d_1184,d_1185,d_1186,d_1187,d_1188,d_1189,d_1190,d_1191,d_1192,d_1193,d_1194,d_1195,d_1196,d_1197,d_1198,d_1199,d_1200,d_1201,d_1202,d_1203,d_1204,d_1205,d_1206,d_1207,d_1208,d_1209,d_1210,d_1211,d_1212,d_1213,d_1214,d_1215,d_1216,d_1217,d_1218,d_1219,d_1220,d_1221,d_1222,d_1223,d_1224,d_1225,d_1226,d_1227,d_1228,d_1229,d_1230,d_1231,d_1232,d_1233,d_1234,d_1235,d_1236,d_1237,d_1238,d_1239,d_1240,d_1241,d_1242,d_1243,d_1244,d_1245,d_1246,d_1247,d_1248,d_1249,d_1250,d_1251,d_1252,d_1253,d_1254,d_1255,d_1256,d_1257,d_1258,d_1259,d_1260,d_1261,d_1262,d_1263,d_1264,d_1265,d_1266,d_1267,d_1268,d_1269,d_1270,d_1271,d_1272,d_1273,d_1274,d_1275,d_1276,d_1277,d_1278,d_1279,d_1280,d_1281,d_1282,d_1283,d_1284,d_1285,d_1286,d_1287,d_1288,d_1289,d_1290,d_1291,d_1292,d_1293,d_1294,d_1295,d_1296,d_1297,d_1298,d_1299,d_1300,d_1301,d_1302,d_1303,d_1304,d_1305,d_1306,d_1307,d_1308,d_1309,d_1310,d_1311,d_1312,d_1313,d_1314,d_1315,d_1316,d_1317,d_1318,d_1319,d_1320,d_1321,d_1322,d_1323,d_1324,d_1325,d_1326,d_1327,d_1328,d_1329,d_1330,d_1331,d_1332,d_1333,d_1334,d_1335,d_1336,d_1337,d_1338,d_1339,d_1340,d_1341,d_1342,d_1343,d_1344,d_1345,d_1346,d_1347,d_1348,d_1349,d_1350,d_1351,d_1352,d_1353,d_1354,d_1355,d_1356,d_1357,d_1358,d_1359,d_1360,d_1361,d_1362,d_1363,d_1364,d_1365,d_1366,d_1367,d_1368,d_1369,d_1370,d_1371,d_1372,d_1373,d_1374,d_1375,d_1376,d_1377,d_1378,d_1379,d_1380,d_1381,d_1382,d_1383,d_1384,d_1385,d_1386,d_1387,d_1388,d_1389,d_1390,d_1391,d_1392,d_1393,d_1394,d_1395,d_1396,d_1397,d_1398,d_1399,d_1400,d_1401,d_1402,d_1403,d_1404,d_1405,d_1406,d_1407,d_1408,d_1409,d_1410,d_1411,d_1412,d_1413,d_1414,d_1415,d_1416,d_1417,d_1418,d_1419,d_1420,d_1421,d_1422,d_1423,d_1424,d_1425,d_1426,d_1427,d_1428,d_1429,d_1430,d_1431,d_1432,d_1433,d_1434,d_1435,d_1436,d_1437,d_1438,d_1439,d_1440,d_1441,d_1442,d_1443,d_1444,d_1445,d_1446,d_1447,d_1448,d_1449,d_1450,d_1451,d_1452,d_1453,d_1454,d_1455,d_1456,d_1457,d_1458,d_1459,d_1460,d_1461,d_1462,d_1463,d_1464,d_1465,d_1466,d_1467,d_1468,d_1469,d_1470,d_1471,d_1472,d_1473,d_1474,d_1475,d_1476,d_1477,d_1478,d_1479,d_1480,d_1481,d_1482,d_1483,d_1484,d_1485,d_1486,d_1487,d_1488,d_1489,d_1490,d_1491,d_1492,d_1493,d_1494,d_1495,d_1496,d_1497,d_1498,d_1499,d_1500,d_1501,d_1502,d_1503,d_1504,d_1505,d_1506,d_1507,d_1508,d_1509,d_1510,d_1511,d_1512,d_1513,d_1514,d_1515,d_1516,d_1517,d_1518,d_1519,d_1520,d_1521,d_1522,d_1523,d_1524,d_1525,d_1526,d_1527,d_1528,d_1529,d_1530,d_1531,d_1532,d_1533,d_1534,d_1535,d_1536,d_1537,d_1538,d_1539,d_1540,d_1541,d_1542,d_1543,d_1544,d_1545,d_1546,d_1547,d_1548,d_1549,d_1550,d_1551,d_1552,d_1553,d_1554,d_1555,d_1556,d_1557,d_1558,d_1559,d_1560,d_1561,d_1562,d_1563,d_1564,d_1565,d_1566,d_1567,d_1568,d_1569,d_1570,d_1571,d_1572,d_1573,d_1574,d_1575,d_1576,d_1577,d_1578,d_1579,d_1580,d_1581,d_1582,d_1583,d_1584,d_1585,d_1586,d_1587,d_1588,d_1589,d_1590,d_1591,d_1592,d_1593,d_1594,d_1595,d_1596,d_1597,d_1598,d_1599,d_1600,d_1601,d_1602,d_1603,d_1604,d_1605,d_1606,d_1607,d_1608,d_1609,d_1610,d_1611,d_1612,d_1613,d_1614,d_1615,d_1616,d_1617,d_1618,d_1619,d_1620,d_1621,d_1622,d_1623,d_1624,d_1625,d_1626,d_1627,d_1628,d_1629,d_1630,d_1631,d_1632,d_1633,d_1634,d_1635,d_1636,d_1637,d_1638,d_1639,d_1640,d_1641,d_1642,d_1643,d_1644,d_1645,d_1646,d_1647,d_1648,d_1649,d_1650,d_1651,d_1652,d_1653,d_1654,d_1655,d_1656,d_1657,d_1658,d_1659,d_1660,d_1661,d_1662,d_1663,d_1664,d_1665,d_1666,d_1667,d_1668,d_1669,d_1670,d_1671,d_1672,d_1673,d_1674,d_1675,d_1676,d_1677,d_1678,d_1679,d_1680,d_1681,d_1682,d_1683,d_1684,d_1685,d_1686,d_1687,d_1688,d_1689,d_1690,d_1691,d_1692,d_1693,d_1694,d_1695,d_1696,d_1697,d_1698,d_1699,d_1700,d_1701,d_1702,d_1703,d_1704,d_1705,d_1706,d_1707,d_1708,d_1709,d_1710,d_1711,d_1712,d_1713,d_1714,d_1715,d_1716,d_1717,d_1718,d_1719,d_1720,d_1721,d_1722,d_1723,d_1724,d_1725,d_1726,d_1727,d_1728,d_1729,d_1730,d_1731,d_1732,d_1733,d_1734,d_1735,d_1736,d_1737,d_1738,d_1739,d_1740,d_1741,d_1742,d_1743,d_1744,d_1745,d_1746,d_1747,d_1748,d_1749,d_1750,d_1751,d_1752,d_1753,d_1754,d_1755,d_1756,d_1757,d_1758,d_1759,d_1760,d_1761,d_1762,d_1763,d_1764,d_1765,d_1766,d_1767,d_1768,d_1769,d_1770,d_1771,d_1772,d_1773,d_1774,d_1775,d_1776,d_1777,d_1778,d_1779,d_1780,d_1781,d_1782,d_1783,d_1784,d_1785,d_1786,d_1787,d_1788,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798,d_1799,d_1800,d_1801,d_1802,d_1803,d_1804,d_1805,d_1806,d_1807,d_1808,d_1809,d_1810,d_1811,d_1812,d_1813,d_1814,d_1815,d_1816,d_1817,d_1818,d_1819,d_1820,d_1821,d_1822,d_1823,d_1824,d_1825,d_1826,d_1827,d_1828,d_1829,d_1830,d_1831,d_1832,d_1833,d_1834,d_1835,d_1836,d_1837,d_1838,d_1839,d_1840,d_1841,d_1842,d_1843,d_1844,d_1845,d_1846,d_1847,d_1848,d_1849,d_1850,d_1851,d_1852,d_1853,d_1854,d_1855,d_1856,d_1857,d_1858,d_1859,d_1860,d_1861,d_1862,d_1863,d_1864,d_1865,d_1866,d_1867,d_1868,d_1869,d_1870,d_1871,d_1872,d_1873,d_1874,d_1875,d_1876,d_1877,d_1878,d_1879,d_1880,d_1881,d_1882,d_1883,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913,d_1914,d_1915,d_1916,d_1917,d_1918,d_1919,d_1920,d_1921,d_1922,d_1923,d_1924,d_1925,d_1926,d_1927,d_1928,d_1929,d_1930,d_1931,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
13519,HOUSEHOLD_2_228_TX_1_evaluation,HOUSEHOLD_2_228,HOUSEHOLD_2,HOUSEHOLD,TX_1,TX,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,2,2,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,2,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,2,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,1,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,2,0,0,0,0,2,3,0,1,0,0,0,0,2,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,2,0,0,0,1,0,0,1,0,2,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,2,0,0,0,2,0,0,0,0,1,2,0,0,0,0,0,0,0,1,1,0,0,2,0,0,0,0,1,0,0,0,2,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,1,1,0,0,1,0,2,0,0,2,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,1,1,0,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,2,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2,0,0,0,2,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,2,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,2,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [47]:
sales.isna().sum()

id          0
item_id     0
dept_id     0
cat_id      0
store_id    0
           ..
d_1937      0
d_1938      0
d_1939      0
d_1940      0
d_1941      0
Length: 1947, dtype: int64

In [51]:
sales['id'].nunique()

30490